const info = [
  {
    "name": "Alabama",
    "cond": "",
    "basic": "",
    "cond_two": "",
    "basic_two": "",
    "premium": "",
    "premium_two": "",
    "body": "No state minimum wage law.",
    "empl": "Employers subject to the Fair Labor Standards Act must pay the current Federal minimum wage of $7.25 per hour.",
  },
  {
    "name": "Alaska",
    "cond": "",
    "basic": "Basic Minimum Rate (per hour): $10.34",
    "basic_two": "",
    "cond_two": "",
    "premium": "Premium Pay After Designated Hours: Daily - 8, Weekly - 40",
    "premium_two": "",
    "body": "Under a voluntary flexible work hour plan approved by the Alaska Department of Labor, a 10 hour day, 40 hour workweek may be instituted with premium pay after 10 hours a day. The premium overtime pay requirement on either a daily or weekly basis is not applicable to employers of fewer than 4 employees. The minimum wage is adjusted annually based on a set formula.",
    "empl": "",
  },
  {
    "name": "Arizona",
    "cond": "",
    "basic": "Basic Minimum Rate (per hour): $12.80",
    "cond_two": "",
    "basic_two": "",
    "premium": "",
    "premium_two": "",
    "body": "",
    "empl": "",
  },
  {
    "name": "Arkansas",
    "cond": "Applicable to employers of 4 or more employees",
    "basic": "Basic Minimum Rate (per hour): $11.00",
    "cond_two": "",
    "basic_two": "",
    "premium": "Premium Pay After Designated Hours: Weekly - 40",
    "premium_two": "",
    "body": "Starting in 2019, the minimum wage will undergo a series of scheduled increases until it reaches $11.00 in 2021.",
    "empl": "",
  },
  {
    "name": "California",
    "cond": "Applicable to employers of 4 or more employees",
    "basic": "Basic Minimum Rate (per hour): $14.00",
    "cond_two": "Applicable to employers with 26 employees or more",
    "basic_two": "Basic Minimum Rate (per hour): $15.00",
    "premium": "Premium Pay After Designated Hours: Daily - 8 Over 12 (double time), Weekly - 40; on 7th day: First 8 hours (time and half) Over 8 hours on 7th day (double time)",
    "premium_two": "",
    "body": "Any work in excess of eight hours in one workday, in excess of 40 hours in one workweek, or in the first eight hours worked on the seventh day of work in any one workweek shall be at the rate of one and one-half times the regular rate of pay. Any work in excess of 12 hours in one day or in excess of eight hours on any seventh day of a workweek shall be paid no less than twice the regular rate of pay. California Labor Code section 510. Exceptions apply to an employee working pursuant to an alternative workweek adopted pursuant to applicable Labor Code sections and for time spent commuting. (See Labor Code section 510 for exceptions). From 2017 through 2023, the minimum wage will increase annually to $15.00/hour on a set schedule and will be adjusted annually thereafter based upon a set formula and the number of employees.",
    "empl": "",
  },
  {
    "name": "Colorado",
    "cond": "",
    "basic": "Basic Minimum Rate (per hour): $12.56",
    "cond_two": "",
    "basic_two": "",
    "premium": "Premium Pay After Designated Hours: Daily - 12, Weekly - 40",
    "premium_two": "",
    "body": "Minimum wage rate and overtime provisions applicable to retail and service, commercial support service, food and beverage, and health and medical industries.",
    "empl": "",
  },
  {
    "name": "Connecticut",
    "cond": "Basic Minimum Rate (per hour): $13.00",
    "basic": "",
    "cond_two": "",
    "basic_two": "",
    "premium": "Premium Pay After Designated Hours: Weekly - 40",
    "premium_two": "",
    "body": "In restaurants and hotel restaurants, for the 7th consecutive day of work, premium pay is required at time and one half the minimum rate. The Connecticut minimum wage rate automatically increases to 0.5 percent above the rate set in the Fair Labor Standards Act if the federal minimum wage rate equals or becomes higher than the State minimum.",
    "empl": "",
  },
  {
    "name": "Delaware",
    "cond": "",
    "basic": "Basic Minimum Rate (per hour): $10.50",
    "cond_two": "",
    "basic_two": "",
    "premium": "",
    "premium_two": "",
    "body": "The State adopts the federal minimum wage rate by reference if the federal rate is greater than the State rate.",
    "empl": "",
  },
  {
    "name": "Florida",
    "cond": "",
    "basic": "Basic Minimum Rate (per hour): $10.00",
    "cond_two": "",
    "basic_two": "",
    "premium": "",
    "premium_two": "",
    "body": "The minimum wage is adjusted annually based on a set formula.",
    "empl": "",
  },
  {
    "name": "Georgia",
    "cond": "Applicable to employers of 6 or more employees",
    "basic": "Basic Minimum Rate (per hour): $5.15",
    "cond_two": "",
    "basic_two": "",
    "premium": "",
    "premium_two": "",
    "body": "The State law excludes from coverage any employment that is subject to the federal Fair Labor Standards Act when the federal rate is greater than the State rate.",
    "empl": "Employers subject to the Fair Labor Standards Act must pay the current Federal minimum wage of $7.25 per hour.",
  },
  {
    "name": "Hawaii",
    "cond": "",
    "basic": "Basic Minimum Rate (per hour): $10.10",
    "cond_two": "",
    "basic_two": "",
    "premium": "Premium Pay After Designated Hours: Weekly - 40",
    "premium_two": "",
    "body": "An employee earning a guaranteed monthly compensation of $2,000 or more is exempt from the State minimum wage and overtime law. Domestic service workers are subject to Hawaii's minimum wage and overtime requirements. Act 248, Regular Session 2013. The State law excludes from coverage any employment that is subject to the federal Fair Labor Standards Act unless the State wage rate is higher than the federal rate.",
    "empl": "",
  },
  {
    "name": "Idaho",
    "cond": "",
    "basic": "Basic Minimum Rate (per hour): $7.25",
    "cond_two": "",
    "basic_two": "",
    "premium": "",
    "premium_two": "",
    "body": "",
    "empl": "",
  },
  {
    "name": "Illinois",
    "cond": "Applicable to employers of 4 or more employees, excluding family members",
    "basic": "Basic Minimum Rate (per hour): $12.00",
    "cond_two": "",
    "basic_two": "",
    "premium": "Premium Pay After Designated Hours: Weekly - 40",
    "premium_two": "",
    "body": "",
    "empl": "",
  },
  {
    "name": "Indiana",
    "cond": "Applicable to employers of 2 or more employees",
    "basic": "Basic Minimum Rate (per hour): $7.25",
    "cond_two": "",
    "basic_two": "",
    "premium": "Premium Pay After Designated Hours: Weekly - 40",
    "premium_two": "",
    "body": "",
    "empl": "",
  },
  {
    "name": "Iowa",
    "cond": "",
    "basic": "Basic Minimum Rate (per hour): $7.25",
    "cond_two": "",
    "basic_two": "",
    "premium": "",
    "premium_two": "",
    "body": "The Iowa minimum wage equals the federal minimum wage rate if it is set below the federal rate.",
    "empl": "",
  },
  {
    "name": "Kansas",
    "cond": "",
    "basic": "Basic Minimum Rate (per hour): $7.25",
    "cond_two": "",
    "basic_two": "",
    "premium": "",
    "premium_two": "",
    "body": "The State law excludes from coverage any employment that is subject to the federal Fair Labor Standards Act.",
    "empl": "",
  },
  {
    "name": "Kentucky",
    "cond": "",
    "basic": "Basic Minimum Rate (per hour): $7.25",
    "cond_two": "",
    "basic_two": "",
    "premium": "Premium Pay After Designated Hours: Weekly - 40, 7th day",
    "premium_two": "",
    "body": "The 7th day overtime law, which is separate from the minimum wage law, requires employers who permit covered employees to work seven days in any one workweek to pay the employee at a rate of time and one-half for hours worked on the seventh day when employees work all seven days of the workweek. The 7th day overtime law does not apply when the employee is not permitted to work over 40 hours total in the workweek. The state adopts the federal minimum wage rate by reference if the federal rate is greater than the State rate. Compensating time in lieu of overtime is allowed upon written request by an employee of any county, charter county, consolidated local government, or urban-county government, including an employee of a county-elected official.",
    "empl": "",
  },
  {
    "name": "Louisiana",
    "cond": "",
    "basic": "",
    "cond_two": "",
    "basic_two": "",
    "premium": "",
    "premium_two": "",
    "body": "No state minimum wage law.",
    "empl": "Employers subject to the Fair Labor Standards Act must pay the current Federal minimum wage of $7.25 per hour.",
  },
  {
    "name": "",
    "cond": "",
    "basic": "",
    "cond_two": "",
    "basic_two": "",
    "premium": "",
    "premium_two": "",
    "body": "",
    "empl": "Employers subject to the Fair Labor Standards Act must pay the current Federal minimum wage of $7.25 per hour.",
  },
  {
    "name": "Maine",
    "cond": "",
    "basic": "Basic Minimum Rate (per hour): $12.75",
    "cond_two": "",
    "basic_two": "",
    "premium": "Premium Pay After Designated Hours: Weekly - 40",
    "premium_two": "",
    "body": "If the highest federal minimum wage is increased in excess of the State minimum wage in effect, then the State minimum wage will increase to the same amount, effective on the same date as the increase in the federal minimum wage. From 2017 through 2020, the minimum wage will increase annually on a set schedule and will be adjusted annually thereafter based on a set formula.",
    "empl": "",
  },
  {
    "name": "Maryland",
    "cond": "",
    "basic": "Basic Minimum Rate (per hour): $12.50",
    "cond_two": "",
    "basic_two": "",
    "premium": "Premium Pay After Designated Hours: Weekly - 40",
    "premium_two": "",
    "body": "The Maryland minimum wage equals the federal minimum wage when set below the federal rate. Employees under 18 years may be paid 85% of the minimum hourly wage rate.",
    "empl": "",
  },
  {
    "name": "Massachusetts",
    "cond": "",
    "basic": "Basic Minimum Rate (per hour): $14.25",
    "cond_two": "",
    "basic_two": "",
    "premium": "Premium Pay After Designated Hours: Weekly - 40",
    "premium_two": "",
    "body": "In no case shall the Massachusetts minimum wage rate be less than $0.50 higher than the effective federal minimum rate.",
    "empl": "",
  },
  {
    "name": "Michigan",
    "cond": "Applicable to employers of 2 or more employees",
    "basic": "Basic Minimum Rate (per hour): $9.87",
    "cond_two": "",
    "basic_two": "",
    "premium": "Premium Pay After Designated Hours: Weekly - 40",
    "premium_two": "",
    "body": "The State law excludes from coverage any employment that is subject to the federal Fair Labor Standards Act unless the State wage rate is higher than the federal rate. From 2019 through 2030, the minimum wage will increase annually on a set schedule, provided the unemployment rate in the preceding year does not exceed 8.5%. Employees 16-17 years of age may be paid 85% of the minimum hourly wage rate.",
    "empl": "",
  },
  {
    "name": "Minnesota",
    "cond": "Large employer (enterprise with annual revenues of $500,000 or more)",
    "basic": "Basic Minimum Rate (per hour): $10.33",
    "cond_two": "Small employer (enterprise with annual revenues of less than $500,000)",
    "basic_two": "Basic Minimum Rate (per hour): $8.42",
    "premium": "Premium Pay After Designated Hours: Weekly - 48",
    "premium_two": "Premium Pay After Designated Hours: Weekly - 48",
    "body": "The minimum wage is adjusted annually based on a set formula. Employees under 18 years may be paid $8.42 per hour",
    "empl": "",
  },
  {
    "name": "Missouri",
    "cond": "",
    "basic": "Basic Minimum Rate (per hour): $11.15",
    "cond_two": "",
    "basic_two": "",
    "premium": "Premium Pay After Designated Hours: Weekly - 40",
    "premium_two": "",
    "body": "In addition to the exemption for federally covered employment, the law exempts, among others, employees of a retail or service business with gross annual sales or business done of less than $500,000. Premium pay required after 52 hours in seasonal amusement or recreation businesses. The minimum wage is adjusted annually based on a set formula. Continuing on from 2019 to 2023, the minimum wage will increase 85 cents per hour each year before reaching $12.00.",
    "empl": "",
  },
  {
    "name": "Mississippi",
    "cond": "",
    "basic": "",
    "cond_two": "",
    "basic_two": "",
    "premium": "",
    "premium_two": "",
    "body": "No state minimum wage law.",
    "empl": "Employers subject to the Fair Labor Standards Act must pay the current Federal minimum wage of $7.25 per hour.",
  },
  
  {
    "name": "Montana",
    "cond": "Business with gross annual sales of more than $110,000",
    "basic": "Basic Minimum Rate (per hour): $9.20",
    "cond_two": "Business not covered by the Fair Labor Standards Act with gross annual sales of $110,000 or less",
    "basic_two": "Basic Minimum Rate (per hour): $4.00",
    "premium": "Premium Pay After Designated Hours: Weekly - 40",
    "premium_two": "Premium Pay After Designated Hours: Weekly - 40",
    "body": "A business not covered by the federal Fair Labor Standards Act whose gross annual sales are $110,000 or less may pay $4.00 per hour. However, if an individual employee is producing or moving goods between states or otherwise covered by the federal Fair Labor Standards Act, that employee must be paid the greater of either the federal minimum wage or Montana's minimum wage. The minimum wage is adjusted annually based on a set formula.",
    "empl": "",
  },
  {
    "name": "North Carolina",
    "cond": "",
    "basic": "Basic Minimum Rate (per hour): $7.25",
    "cond_two": "",
    "basic_two": "",
    "premium": "Premium Pay After Designated Hours: Weekly - 40",
    "premium_two": "",
    "body": "Premium pay is required after 45 hours a week in seasonal amusements or recreational establishments.",
    "empl": "",
  },
  {
    "name": "North Dakota",
    "cond": "",
    "basic": "Basic Minimum Rate (per hour): $7.25",
    "cond_two": "",
    "basic_two": "",
    "premium": "Premium Pay After Designated Hours: Weekly - 40",
    "premium_two": "",
    "body": "",
    "empl": "",
  },
  {
    "name": "Nebraska",
    "cond": "Applicable to employers of 4 or more employees",
    "basic": "Basic Minimum Rate (per hour): $9.00",
    "cond_two": "",
    "basic_two": "",
    "premium": "",
    "premium_two": "",
    "body": "",
    "empl": "",
  },
  {
    "name": "New Hampshire",
    "cond": "",
    "basic": "Basic Minimum Rate (per hour): $7.25",
    "cond_two": "",
    "basic_two": "",
    "premium": "Premium Pay After Designated Hours: Weekly - 40",
    "premium_two": "",
    "body": "The New Hampshire minimum wage equals the federal minimum wage when set below the federal rate.",
    "empl": "",
  },
  {
    "name": "New Jersey",
    "cond": "",
    "basic": "Basic Minimum Rate (per hour): $13.00",
    "cond_two": "",
    "basic_two": "",
    "premium": "Premium Pay After Designated Hours: Weekly - 40",
    "premium_two": "",
    "body": "The minimum wage is adjusted annually based on a set formula. There is a minimum wage of $11.90 per hour for seasonal and small employers who employee fewer than 6 people.",
    "empl": "",
  },
  {
    "name": "New Mexico",
    "cond": "",
    "basic": "Basic Minimum Rate (per hour): $11.50",
    "cond_two": "",
    "basic_two": "",
    "premium": "Premium Pay After Designated Hours: Weekly - 40",
    "premium_two": "",
    "body": "",
    "empl": "",
  },
  {
    "name": "Nevada",
    "cond": "With no health ins. benefits provided by employer",
    "basic": "Basic Minimum Rate (per hour): $9.75",
    "cond_two": "With health ins. benefits provided by employer and received by employee",
    "basic_two": "Basic Minimum Rate (per hour): $8.75",
    "premium": "",
    "premium_two": "",
    "body": "The minimum wage is adjusted annually based on a set formula.",
    "empl": "",
  },
  {
    "name": "New York",
    "cond": "",
    "basic": "Basic Minimum Rate (per hour): $13.20; $15.00 (Long Island, Westchester, & NYC)",
    "cond_two": "",
    "basic_two": "",
    "premium": "Premium Pay After Designated Hours: Weekly - 40",
    "premium_two": "",
    "body": "These rates are in effect from December 31, 2021 through December 30, 2022. View minimum wage rates through 2022. The New York minimum wage equals the federal minimum wage when set below the federal rate. Under the new hospitality regulations, residential workers (\"live-in workers\") are now entitled to overtime for hours worked over 40 in a payroll week, instead of the prior 44 hour requirement. Therefore, overtime hours for all non-exempt workers are now any hours worked over 40 in a payroll week. Employers operating a factory, mercantile establishment, hotel, restaurant, freight/passenger elevator, or theater; or a building employing security guards, janitors, superintendents, managers, engineers, or firemen must provide 24 hours of consecutive rest each week. Domestic workers are entitled to 24 hours of consecutive rest each week, and receive premium pay if they work during such period. Employees receive 1 hour of pay at minimum wage rate in addition to owed wages when spread of hours exceeds 10 hours, there is a split shift, or both.",
    "empl": "",
  },
  {
    "name": "Ohio",
    "cond": "Employers with annual gross receipts of $342,000 or more",
    "basic": "Basic Minimum Rate (per hour): $9.30",
    "cond_two": "Employers with annual gross receipts under $342,000",
    "basic_two": "Basic Minimum Rate (per hour): $7.25",
    "premium": "Premium Pay After Designated Hours: Weekly - 40",
    "premium_two": "Premium Pay After Designated Hours: Weekly - 40",
    "body": "The minimum wage is adjusted annually based on a set formula",
    "empl": "",
  },
  {
    "name": "Oklahoma",
    "cond": "Employers of ten or more full time employees at any one location and employers with annual gross sales over $100,000 irrespective of number of full time employees",
    "basic": "Basic Minimum Rate (per hour): $7.25",
    "cond_two": "All other employers",
    "basic_two": "Basic Minimum Rate (per hour): $2.00",
    "premium": "",
    "premium_two": "",
    "body": "The Oklahoma state minimum wage law does not contain current dollar minimums. Instead the state adopts the federal minimum wage rate by reference. The State law excludes from coverage any employment that is subject to the federal Fair Labor Standards Act.",
    "empl": "",
  },
  {
    "name": "Oregon",
    "cond": "",
    "basic": "Basic Minimum Rate (per hour): $12.75",
    "cond_two": "",
    "basic_two": "",
    "premium": "Premium Pay After Designated Hours: Weekly - 40",
    "premium_two": "",
    "body": "Premium pay required after 10 hours a day in nonfarm canneries, driers, or packing plants and in mills, factories or manufacturing establishments (excluding sawmills, planning mills, shingle mills, and logging camps). From 2016 through 2022, the minimum wage will increase annually on a set schedule and will be adjusted annually thereafter based on a set formula.",
    "empl": "",
  },
  {
    "name": "Pennsylvania",
    "cond": "",
    "basic": "Basic Minimum Rate (per hour): $7.25",
    "cond_two": "",
    "basic_two": "",
    "premium": "Premium Pay After Designated Hours: Weekly - 40",
    "premium_two": "",
    "body": "",
    "empl": "",
  },
  {
    "name": "Rhode Island",
    "cond": "",
    "basic": "Basic Minimum Rate (per hour): $12.25",
    "cond_two": "",
    "basic_two": "",
    "premium": "Premium Pay After Designated Hours: Weekly - 40",
    "premium_two": "",
    "body": "Time and one-half premium pay for work on Sundays and holidays in retail and certain other businesses is required under two laws that are separate from the minimum wage law.",
    "empl": "",
  },
  {
    "name": "South Carolina",
    "cond": "",
    "basic": "",
    "cond_two": "",
    "basic_two": "",
    "premium": "",
    "premium_two": "",
    "body": "No state minimum wage law.",
    "empl": "Employers subject to the Fair Labor Standards Act must pay the current Federal minimum wage of $7.25 per hour.",
  },
  {
    "name": "South Dakota",
    "cond": "",
    "basic": "Basic Minimum Rate (per hour): $9.95",
    "cond_two": "",
    "basic_two": "",
    "premium": "",
    "premium_two": "",
    "body": "The minimum wage is adjusted annually based on a set formula.",
    "empl": "",
  },
  {
    "name": "Tennessee",
    "cond": "",
    "basic": "",
    "cond_two": "",
    "basic_two": "",
    "premium": "",
    "premium_two": "",
    "body": "No state minimum wage law.",
    "empl": "Employers subject to the Fair Labor Standards Act must pay the current Federal minimum wage of $7.25 per hour.",
  },
  {
    "name": "Texas",
    "cond": "",
    "basic": "Basic Minimum Rate (per hour): $7.25",
    "cond_two": "",
    "basic_two": "",
    "premium": "",
    "premium_two": "",
    "body": "The State law excludes from coverage any employment that is subject to the federal Fair Labor Standards Act. The Texas State minimum wage law does not contain current dollar minimums. Instead the State adopts the federal minimum wage rate by reference.",
    "empl": "",
  },
  {
    "name": "Utah",
    "cond": "",
    "basic": "Basic Minimum Rate (per hour): $7.25",
    "cond_two": "",
    "basic_two": "",
    "premium": "",
    "premium_two": "",
    "body": "The Utah state minimum wage law does not contain current dollar minimums. Instead the state law authorizes the adoption of the federal minimum wage rate via administrative action. The State law excludes from coverage any employment that is subject to the federal Fair Labor Standards Act.",
    "empl": "",
  },
  {
    "name": "Virginia",
    "cond": "Applicable to employers of 4 or more employees",
    "basic": "Basic Minimum Rate (per hour): $11.00",
    "cond_two": "",
    "basic_two": "",
    "premium": "",
    "premium_two": "",
    "body": "",
    "empl": "",
  },
  {
    "name": "Vermont",
    "cond": "Applicable to employers of two or more employees",
    "basic": "Basic Minimum Rate (per hour): $12.55",
    "cond_two": "",
    "basic_two": "",
    "premium": "Premium Pay After Designated Hours: Weekly - 40",
    "premium_two": "",
    "body": "The Vermont minimum wage is automatically replaced with the federal minimum wage rate if it is higher than the State minimum.",
    "empl": "",
  },
  {
    "name": "Washington",
    "cond": "",
    "basic": "Basic Minimum Rate (per hour): $14.49",
    "cond_two": "",
    "basic_two": "",
    "premium": "Premium Pay After Designated Hours: Weekly - 40",
    "premium_two": "",
    "body": "Premium pay not applicable to employees who request compensating time off in lieu of premium pay. From 2017 through 2020, the minimum wage will increase annually on a set schedule and will be adjusted annually thereafter based on a set formula.",
    "empl": "",
  },
  {
    "name": "Wisconsin",
    "cond": "",
    "basic": "Basic Minimum Rate (per hour): $7.25",
    "cond_two": "",
    "basic_two": "",
    "premium": "Premium Pay After Designated Hours: Weekly - 40",
    "premium_two": "",
    "body": "",
    "empl": "",
  },
  {
    "name": "West Virginia",
    "cond": "Applicable to employers of 6 or more employees at one location",
    "basic": "Basic Minimum Rate (per hour): $8.75",
    "cond_two": "",
    "basic_two": "",
    "premium": "Premium Pay After Designated Hours 1 : Weekly - 40",
    "premium_two": "",
    "body": "",
    "empl": "",
  },
  {
    "name": "Wyoming",
    "cond": "",
    "basic": "Basic Minimum Rate (per hour): $5.15",
    "cond_two": "",
    "basic_two": "",
    "premium": "",
    "premium_two": "",
    "body": "",
    "empl": "Employers subject to the Fair Labor Standards Act must pay the current Federal minimum wage of $7.25 per hour.",
  },
  {
    "name": "District of Columbia",
    "cond": "",
    "basic": "Basic Minimum Rate (per hour): $15.20",
    "cond_two": "",
    "basic_two": "",
    "premium": "Premium Pay After Designated Hours: Weekly - 40",
    "premium_two": "",
    "body": "From 2017 through 2020, the minimum wage will increase annually on a set schedule and will be adjusted annually thereafter based on a set formula.",
    "empl": "",
  },
  {
    "name": "Commonwealth of the Northern Mariana Islands",
    "cond": "",
    "basic": "Basic Minimum Rate (per hour): $7.25",
    "cond_two": "",
    "basic_two": "",
    "premium": "",
    "premium_two": "",
    "body": "The Commonwealth of the Northern Mariana Islands has special minimum wage rates.",
    "empl": "",
  },
  {
    "name": "Puerto Rico",
    "cond": "Employees covered by the FLSA",
    "basic": "Basic Minimum Rate (per hour): $8.50",
    "cond_two": "Employees not covered by the FLSA",
    "basic_two": "Basic Minimum Rate (per hour): $5.08",
    "premium": "Premium Pay After Designated Hours: Daily - 8, And on statutory rest day (double time), Weekly - 40 (double time)",
    "premium_two": "Premium Pay After Designated Hours: Daily - 8, And on statutory rest day (double time), Weekly - 40 (double time)",
    "body": "Employers covered by the federal Fair Labor Standards Act (FLSA) are subject only to the federal minimum wage and all applicable regulations. Employers not covered by the FLSA will be subject to a minimum wage that is at least 70 percent of the federal minimum wage or the applicable mandatory decree rate, whichever is higher. The Secretary of Labor and Human Resources may authorize a rate based on a lower percentage for any employer who can show that implementation of the 70 percent rate would substantially curtail employment in that business.",
    "empl": "",
  },
  {
    "name": "American Samoa",
    "cond": "",
    "basic": "",
    "cond_two": "",
    "basic_two": "",
    "premium": "",
    "premium_two": "",
    "body": "American Samoa has special minimum wage rates .",
    "empl": "",
  },
  {
    "name": "Virgin Islands",
    "cond": "State law",
    "basic": "Basic Minimum Rate (per hour): $10.50",
    "cond_two": "",
    "basic_two": "",
    "premium": "",
    "premium_two": "",
    "body": "",
    "empl": "",
  },
  {
    "name": "Guam",
    "cond": "",
    "basic": "Basic Minimum Rate (per hour): $8.75",
    "cond_two": "",
    "basic_two": "",
    "premium": "Premium Pay After Designated Hours: Weekly - 40",
    "premium_two": "",
    "body": "",
    "empl": "",
  },

]

export default info;